{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "3b8cc2c4-3c72-4b77-8a72-9896b2251b52",
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "from pathlib import Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "87d03fc5-1752-49cb-bcef-a454b415dd8e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "File loaded: 8026-1G-LNE_original.PKT\n",
      "Total lines: 338\n",
      "\n",
      "First 10 lines:\n",
      "\n",
      "  RTCM-Ref 4095      33443618.160 5783662.591 \"    \"\n",
      "RTCM-Ref 4095(1)      33443615.671 5783662.020 \"    \"\n",
      "RTCM-Ref 4095(2)      33443619.253 5783729.320 \"    \"\n",
      "RTCM-Ref 4095(3)      33443677.075 5783652.276 \"    \"\n",
      "RTCM-Ref 4095(4)      33443613.573 5783692.426 \"    \"\n",
      "           1001   33 33448194.045 5781632.418 \"BP    \"\n",
      "           1002   33 33448194.026 5781632.404 \"BP    \"\n",
      "           1003    2 33448204.923 5781639.303 \"    \"\n",
      "           1004    2 33448212.500 5781631.779 \"    \"\n",
      "           1005    2 33448210.968 5781629.578 \"    \"\n"
     ]
    }
   ],
   "source": [
    "# Change this to your file\n",
    "# Enter the full path to your PKT file\n",
    "pkt_path = Path(r\"C:\\Users\\praka\\Desktop\\txt_file\\8026-1G-LNE_original.PKT\")\n",
    "\n",
    "# Check if the file exists\n",
    "if not pkt_path.exists():\n",
    "    raise FileNotFoundError(f\"File not found:\\n{pkt_path}\")\n",
    "\n",
    "# Read the file\n",
    "with open(pkt_path, \"r\", encoding=\"latin-1\") as f:\n",
    "    lines = f.readlines()\n",
    "\n",
    "print(f\"File loaded: {pkt_path.name}\")\n",
    "print(f\"Total lines: {len(lines)}\")\n",
    "\n",
    "print(\"\\nFirst 10 lines:\\n\")\n",
    "\n",
    "for line in lines[:10]:\n",
    "    print(line.rstrip())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e8878ce3-5985-4c04-8166-e82372590abb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "GEOGRAF ASSISTANT\n",
      "============================================================\n",
      "\n",
      "Input File : C:\\Users\\praka\\Desktop\\txt_file\\8026-1G-LNE_original.PKT\n",
      "Records    : 338\n",
      "\n",
      "Starting processing...\n",
      "\n",
      "------------------------------------------------------------\n",
      "Record : 1\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 2\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 3\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 4\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 5\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 6\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 7\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 8\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 9\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 10\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 11\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 12\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 13\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 14\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 15\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 16\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 17\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 18\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 19\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 20\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 21\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 22\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 23\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 24\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 25\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 26\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 27\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 28\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 29\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 30\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 31\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 32\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 33\n",
      "Original : \"11    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"11\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 34\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 35\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 36\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 37\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 38\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 39\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 40\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 41\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 42\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 43\n",
      "Original : \"BOESCHUNGS OBERKANTE IST GL. ZAUN    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BOESCHUNGS OBERKANTE IST GL. ZAUN    \"\n",
      "------------------------------------------------------------\n",
      "Record : 44\n",
      "Original : \"BOESCHUNGS OBERKANTE IST GL. ZAUN    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BOESCHUNGS OBERKANTE IST GL. ZAUN    \"\n",
      "------------------------------------------------------------\n",
      "Record : 45\n",
      "Original : \"12    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"12\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 46\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 47\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 48\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 49\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 50\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 51\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 52\n",
      "Original : \"SCHACHT EWE    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"SCHACHT EWE    \"\n",
      "------------------------------------------------------------\n",
      "Record : 53\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 54\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 55\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 56\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 57\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 58\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 59\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 60\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 61\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 62\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 63\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 64\n",
      "Original : \"72    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"72\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 65\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 66\n",
      "Original : \"BOK ENDET HIER MIT BUK    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BOK ENDET HIER MIT BUK    \"\n",
      "------------------------------------------------------------\n",
      "Record : 67\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 68\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 69\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 70\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 71\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 72\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 73\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 74\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 75\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 76\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 77\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 78\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 79\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 80\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 81\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 82\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 83\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 84\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 85\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 86\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 87\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 88\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 89\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 90\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 91\n",
      "Original : \"13    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"13\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 92\n",
      "Original : \"23    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"23\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 93\n",
      "Original : \"23    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"23\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 94\n",
      "Original : \"73    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"73\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 95\n",
      "Original : \"ELEKTROSTATIONGEBAEUDE    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"ELEKTROSTATIONGEBAEUDE    \"\n",
      "------------------------------------------------------------\n",
      "Record : 96\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 97\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 98\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 99\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 100\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 101\n",
      "Original : \"2113    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"2113\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 102\n",
      "Original : \"2173    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"2173\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 103\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 104\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 105\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 106\n",
      "Original : \"15    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"15\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 107\n",
      "Original : \"75    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"75\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 108\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 109\n",
      "Original : \"15    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"15\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 110\n",
      "Original : \"75    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"75\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 111\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 112\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 113\n",
      "Original : \"16    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"16\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 114\n",
      "Original : \"76    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"76\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 115\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 116\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 117\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 118\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 119\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 120\n",
      "Original : \"LÄ 0.400 4.000 einstämmig \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"0 400 4 000\"\n",
      "Sach     : \"LÄ . . einstämmig\"\n",
      "------------------------------------------------------------\n",
      "Record : 121\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 122\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 123\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 124\n",
      "Original : \"15    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"15\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 125\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 126\n",
      "Original : \"GEBUESCHFLAECHE    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"GEBUESCHFLAECHE    \"\n",
      "------------------------------------------------------------\n",
      "Record : 127\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 128\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 129\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 130\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 131\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 132\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 133\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 134\n",
      "Original : \"75    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"75\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 135\n",
      "Original : \"FI 1.000 7.000 einstämmig \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"1 000 7 000\"\n",
      "Sach     : \"FI . . einstämmig\"\n",
      "------------------------------------------------------------\n",
      "Record : 136\n",
      "Original : \"KI 1.200 7.000 einstämmig \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"1 200 7 000\"\n",
      "Sach     : \"KI . . einstämmig\"\n",
      "------------------------------------------------------------\n",
      "Record : 137\n",
      "Original : \"TA 0.800 5.000 einstämmig \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"0 800 5 000\"\n",
      "Sach     : \"TA . . einstämmig\"\n",
      "------------------------------------------------------------\n",
      "Record : 138\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 139\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 140\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 141\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 142\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 143\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 144\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 145\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 146\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 147\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 148\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 149\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 150\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 151\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 152\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 153\n",
      "Original : \"OKRFEG    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"OKRFEG    \"\n",
      "------------------------------------------------------------\n",
      "Record : 154\n",
      "Original : \"12    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"12\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 155\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 156\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 157\n",
      "Original : \"72    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"72\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 158\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 159\n",
      "Original : \"Treppe    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"Treppe    \"\n",
      "------------------------------------------------------------\n",
      "Record : 160\n",
      "Original : \"12    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"12\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 161\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 162\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 163\n",
      "Original : \"82    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"82\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 164\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 165\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 166\n",
      "Original : \"12    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"12\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 167\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 168\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 169\n",
      "Original : \"82    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"82\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 170\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 171\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 172\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 173\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 174\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 175\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 176\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 177\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 178\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 179\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 180\n",
      "Original : \"15    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"15\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 181\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 182\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 183\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 184\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 185\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 186\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 187\n",
      "Original : \"25    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"25\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 188\n",
      "Original : \"75    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"75\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 189\n",
      "Original : \"16    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"16\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 190\n",
      "Original : \"26    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"26\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 191\n",
      "Original : \"26    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"26\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 192\n",
      "Original : \"2617    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"2617\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 193\n",
      "Original : \"26    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"26\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 194\n",
      "Original : \"76    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"76\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 195\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 196\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 197\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 198\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 199\n",
      "Original : \"71    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"71\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 200\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 201\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 202\n",
      "Original : \"16    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"16\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 203\n",
      "Original : \"26    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"26\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 204\n",
      "Original : \"26    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"26\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 205\n",
      "Original : \"76    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"76\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 206\n",
      "Original : \"16    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"16\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 207\n",
      "Original : \"2611    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"2611\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 208\n",
      "Original : \"71    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"71\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 209\n",
      "Original : \"2611    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"2611\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 210\n",
      "Original : \"2112    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"2112\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 211\n",
      "Original : \"71    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"71\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 212\n",
      "Original : \"Treppe    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"Treppe    \"\n",
      "------------------------------------------------------------\n",
      "Record : 213\n",
      "Original : \"Treppe    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"Treppe    \"\n",
      "------------------------------------------------------------\n",
      "Record : 214\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 215\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 216\n",
      "Original : \"SCHOTTER    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"SCHOTTER    \"\n",
      "------------------------------------------------------------\n",
      "Record : 217\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 218\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 219\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 220\n",
      "Original : \"7227    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"7227\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 221\n",
      "Original : \"76    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"76\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 222\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 223\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 224\n",
      "Original : \"STUETZMAUER    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"STUETZMAUER    \"\n",
      "------------------------------------------------------------\n",
      "Record : 225\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 226\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 227\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 228\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 229\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 230\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 231\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 232\n",
      "Original : \"WASSERDURCHLAESSIG.BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"WASSERDURCHLAESSIG.BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 233\n",
      "Original : \"WASSERDURCHLAESSIG.BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"WASSERDURCHLAESSIG.BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 234\n",
      "Original : \"WASSERDURCHLAESSIG.BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"WASSERDURCHLAESSIG.BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 235\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 236\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 237\n",
      "Original : \"11    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"11\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 238\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 239\n",
      "Original : \"71    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"71\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 240\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 241\n",
      "Original : \"1112    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"1112\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 242\n",
      "Original : \"71    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"71\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 243\n",
      "Original : \"11    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"11\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 244\n",
      "Original : \"REGENRINNE.B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"REGENRINNE.B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 245\n",
      "Original : \"REGENRINNE.B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"REGENRINNE.B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 246\n",
      "Original : \"REGENRINNE.B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"REGENRINNE.B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 247\n",
      "Original : \"21    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"21\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 248\n",
      "Original : \"13    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"13\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 249\n",
      "Original : \"23    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"23\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 250\n",
      "Original : \"7371    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"7371\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 251\n",
      "Original : \"REGENRINNE.B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"REGENRINNE.B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 252\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 253\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 254\n",
      "Original : \"2213    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"2213\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 255\n",
      "Original : \"23    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"23\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 256\n",
      "Original : \"23    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"23\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 257\n",
      "Original : \"73    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"73\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 258\n",
      "Original : \"RG    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"RG    \"\n",
      "------------------------------------------------------------\n",
      "Record : 259\n",
      "Original : \"RG    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"RG    \"\n",
      "------------------------------------------------------------\n",
      "Record : 260\n",
      "Original : \"2213    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"2213\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 261\n",
      "Original : \"23    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"23\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 262\n",
      "Original : \"23    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"23\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 263\n",
      "Original : \"7322    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"7322\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 264\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 265\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 266\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 267\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 268\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 269\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 270\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 271\n",
      "Original : \"32    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"32\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 272\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 273\n",
      "Original : \"32    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"32\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 274\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 275\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 276\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 277\n",
      "Original : \"AS    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"AS    \"\n",
      "------------------------------------------------------------\n",
      "Record : 278\n",
      "Original : \"AS    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"AS    \"\n",
      "------------------------------------------------------------\n",
      "Record : 279\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 280\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 281\n",
      "Original : \"AS    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"AS    \"\n",
      "------------------------------------------------------------\n",
      "Record : 282\n",
      "Original : \"AS    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"AS    \"\n",
      "------------------------------------------------------------\n",
      "Record : 283\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 284\n",
      "Original : \"72    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"72\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 285\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 286\n",
      "Original : \"12    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"12\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 287\n",
      "Original : \"19    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"19\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 288\n",
      "Original : \"79    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"79\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 289\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 290\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 291\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 292\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 293\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 294\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 295\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 296\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 297\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 298\n",
      "Original : \"22    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"22\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 299\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 300\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 301\n",
      "Original : \"72    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"72\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 302\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 303\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 304\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 305\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 306\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 307\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 308\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 309\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 310\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 311\n",
      "Original : \"77    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"77\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 312\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 313\n",
      "Original : \"BP    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"BP    \"\n",
      "------------------------------------------------------------\n",
      "Record : 314\n",
      "Original : \"METALL.GEGENFAHRSCHUTZ 11   \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"11\"\n",
      "Sach     : \"METALL.GEGENFAHRSCHUTZ\"\n",
      "------------------------------------------------------------\n",
      "Record : 315\n",
      "Original : \"METALL.GEGENFAHRSCHUTZ 71   \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"71\"\n",
      "Sach     : \"METALL.GEGENFAHRSCHUTZ\"\n",
      "------------------------------------------------------------\n",
      "Record : 316\n",
      "Original : \"METALL.GEGENFAHRSCHUTZ 11   \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"11\"\n",
      "Sach     : \"METALL.GEGENFAHRSCHUTZ\"\n",
      "------------------------------------------------------------\n",
      "Record : 317\n",
      "Original : \"METALL.GEGENFAHRSCHUTZ 71   \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"71\"\n",
      "Sach     : \"METALL.GEGENFAHRSCHUTZ\"\n",
      "------------------------------------------------------------\n",
      "Record : 318\n",
      "Original : \"METALL.GEGENFAHRSCHUTZ 11   \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"11\"\n",
      "Sach     : \"METALL.GEGENFAHRSCHUTZ\"\n",
      "------------------------------------------------------------\n",
      "Record : 319\n",
      "Original : \"METALL.GEGENFAHRSCHUTZ 71   \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"71\"\n",
      "Sach     : \"METALL.GEGENFAHRSCHUTZ\"\n",
      "------------------------------------------------------------\n",
      "Record : 320\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 321\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 322\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 323\n",
      "Original : \"B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 324\n",
      "Original : \"B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 325\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 326\n",
      "Original : \"B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 327\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 328\n",
      "Original : \"    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"    \"\n",
      "------------------------------------------------------------\n",
      "Record : 329\n",
      "Original : \"18    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"18\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 330\n",
      "Original : \"19    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"19\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 331\n",
      "Original : \"B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 332\n",
      "Original : \"28    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"28\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 333\n",
      "Original : \"B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 334\n",
      "Original : \"29    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"29\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 335\n",
      "Original : \"78    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"78\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 336\n",
      "Original : \"B    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"B    \"\n",
      "------------------------------------------------------------\n",
      "Record : 337\n",
      "Original : \"79    \"\n",
      "Decision : SPLIT\n",
      "LNA      : \"79\"\n",
      "Sach     : \"\"\n",
      "------------------------------------------------------------\n",
      "Record : 338\n",
      "Original : \"WASSERRINNE    \"\n",
      "Decision : SACH_ONLY\n",
      "Sach     : \"WASSERRINNE    \"\n",
      "\n",
      "============================================================\n",
      "Finished\n",
      "============================================================\n",
      "\n",
      "LNA file  : C:\\Users\\praka\\Desktop\\txt_file\\8026-1G-LNA_TEST.PKT\n",
      "Sach file : C:\\Users\\praka\\Desktop\\txt_file\\8026-1G-Sach_TEST.PKT\n",
      "\n",
      "LNA records  : 154\n",
      "Sach records : 338\n"
     ]
    }
   ],
   "source": [
    "# ==========================================================\n",
    "# Geograf Assistant v0.1\n",
    "# PART 1\n",
    "# ==========================================================\n",
    "\n",
    "from pathlib import Path\n",
    "import re\n",
    "\n",
    "\n",
    "class GeografAssistant:\n",
    "\n",
    "    def __init__(self, pkt_file):\n",
    "\n",
    "        self.input_file = Path(pkt_file)\n",
    "\n",
    "        if not self.input_file.exists():\n",
    "            raise FileNotFoundError(f\"\\nFile not found:\\n{self.input_file}\")\n",
    "\n",
    "        self.output_folder = self.input_file.parent\n",
    "\n",
    "        filename = self.input_file.name\n",
    "\n",
    "        # Remove \"-LNE.PKT\" or \"-LNE_original.PKT\"\n",
    "        base_name = re.sub(\n",
    "            r'-LNE(_original)?\\.PKT$',\n",
    "            '',\n",
    "            filename,\n",
    "            flags=re.IGNORECASE\n",
    "        )\n",
    "\n",
    "        self.lna_file = self.output_folder / f\"{base_name}-LNA_TEST.PKT\"\n",
    "        self.sach_file = self.output_folder / f\"{base_name}-Sach_TEST.PKT\"\n",
    "\n",
    "        self.lines = []\n",
    "\n",
    "    # =======================================================\n",
    "    # Read File\n",
    "    # =======================================================\n",
    "\n",
    "    def read_file(self):\n",
    "\n",
    "        with open(self.input_file, \"r\", encoding=\"latin-1\") as f:\n",
    "            self.lines = f.readlines()\n",
    "\n",
    "        print(\"=\" * 60)\n",
    "        print(\"GEOGRAF ASSISTANT\")\n",
    "        print(\"=\" * 60)\n",
    "\n",
    "        print(f\"\\nInput File : {self.input_file}\")\n",
    "        print(f\"Records    : {len(self.lines)}\")\n",
    "\n",
    "    # =======================================================\n",
    "    # Extract quoted text\n",
    "    # =======================================================\n",
    "\n",
    "    def get_text(self, line):\n",
    "\n",
    "        first = line.find('\"')\n",
    "        last = line.rfind('\"')\n",
    "\n",
    "        if first == -1 or last == -1 or first == last:\n",
    "            return \"\"\n",
    "\n",
    "        return line[first + 1:last]\n",
    "\n",
    "    # =======================================================\n",
    "    # Replace quoted text\n",
    "    # =======================================================\n",
    "\n",
    "    def replace_text(self, line, new_text):\n",
    "\n",
    "        first = line.find('\"')\n",
    "        last = line.rfind('\"')\n",
    "\n",
    "        if first == -1 or last == -1 or first == last:\n",
    "            return line\n",
    "\n",
    "        return line[:first + 1] + new_text + line[last:]\n",
    "\n",
    "    # =======================================================\n",
    "    # Detect numbers\n",
    "    # =======================================================\n",
    "\n",
    "    def extract_numbers(self, text):\n",
    "\n",
    "        return re.findall(r'\\b\\d+\\b', text)\n",
    "\n",
    "    # =======================================================\n",
    "    # Remove numbers\n",
    "    # =======================================================\n",
    "\n",
    "    def remove_numbers(self, text):\n",
    "\n",
    "        text = re.sub(r'\\b\\d+\\b', '', text)\n",
    "\n",
    "        # remove duplicate spaces\n",
    "        text = re.sub(r'\\s+', ' ', text)\n",
    "\n",
    "        return text.strip()\n",
    "\n",
    "    # =======================================================\n",
    "    # Rule Engine (Version 0.1)\n",
    "    # =======================================================\n",
    "\n",
    "    def classify(self, text):\n",
    "\n",
    "        # Empty text\n",
    "        if text == \"\":\n",
    "\n",
    "            return {\n",
    "                \"decision\": \"LNA_ONLY\",\n",
    "                \"lna\": \"\",\n",
    "                \"sach\": None\n",
    "            }\n",
    "\n",
    "        numbers = self.extract_numbers(text)\n",
    "\n",
    "        # Text only\n",
    "        if len(numbers) == 0:\n",
    "\n",
    "            return {\n",
    "                \"decision\": \"SACH_ONLY\",\n",
    "                \"lna\": None,\n",
    "                \"sach\": text\n",
    "            }\n",
    "\n",
    "        # Text + Numbers\n",
    "        sach = self.remove_numbers(text)\n",
    "\n",
    "        lna = \" \".join(numbers)\n",
    "\n",
    "        return {\n",
    "            \"decision\": \"SPLIT\",\n",
    "            \"lna\": lna,\n",
    "            \"sach\": sach\n",
    "        }\n",
    "\n",
    "    # =======================================================\n",
    "    # Log\n",
    "    # =======================================================\n",
    "\n",
    "    def print_log(self, line_number, original, result):\n",
    "\n",
    "        print(\"-\" * 60)\n",
    "\n",
    "        print(f\"Record : {line_number}\")\n",
    "\n",
    "        print(f'Original : \"{original}\"')\n",
    "\n",
    "        print(f'Decision : {result[\"decision\"]}')\n",
    "\n",
    "        if result[\"lna\"] is not None:\n",
    "            print(f'LNA      : \"{result[\"lna\"]}\"')\n",
    "\n",
    "        if result[\"sach\"] is not None:\n",
    "            print(f'Sach     : \"{result[\"sach\"]}\"')\n",
    "\n",
    "    # =======================================================\n",
    "    # Process File\n",
    "    # =======================================================\n",
    "\n",
    "    def process(self):\n",
    "\n",
    "        self.read_file()\n",
    "\n",
    "        lna_lines = []\n",
    "        sach_lines = []\n",
    "\n",
    "        print(\"\\nStarting processing...\\n\")\n",
    "\n",
    "        for i, line in enumerate(self.lines, start=1):\n",
    "\n",
    "            # Keep original formatting\n",
    "            original_line = line.rstrip(\"\\n\")\n",
    "\n",
    "            # Skip completely empty lines\n",
    "            if original_line.strip() == \"\":\n",
    "                continue\n",
    "\n",
    "            text = self.get_text(original_line)\n",
    "\n",
    "            result = self.classify(text)\n",
    "\n",
    "            self.print_log(i, text, result)\n",
    "\n",
    "            # ----------------------------\n",
    "            # LNA\n",
    "            # ----------------------------\n",
    "            if result[\"decision\"] == \"LNA_ONLY\":\n",
    "\n",
    "                new_line = self.replace_text(\n",
    "                    original_line,\n",
    "                    result[\"lna\"]\n",
    "                )\n",
    "\n",
    "                lna_lines.append(new_line)\n",
    "\n",
    "            # ----------------------------\n",
    "            # Sach\n",
    "            # ----------------------------\n",
    "            elif result[\"decision\"] == \"SACH_ONLY\":\n",
    "\n",
    "                new_line = self.replace_text(\n",
    "                    original_line,\n",
    "                    result[\"sach\"]\n",
    "                )\n",
    "\n",
    "                sach_lines.append(new_line)\n",
    "\n",
    "            # ----------------------------\n",
    "            # Split\n",
    "            # ----------------------------\n",
    "            elif result[\"decision\"] == \"SPLIT\":\n",
    "\n",
    "                lna_line = self.replace_text(\n",
    "                    original_line,\n",
    "                    result[\"lna\"]\n",
    "                )\n",
    "\n",
    "                sach_line = self.replace_text(\n",
    "                    original_line,\n",
    "                    result[\"sach\"]\n",
    "                )\n",
    "\n",
    "                lna_lines.append(lna_line)\n",
    "                sach_lines.append(sach_line)\n",
    "\n",
    "        # ===================================================\n",
    "        # Write LNA\n",
    "        # ===================================================\n",
    "\n",
    "        with open(self.lna_file, \"w\", encoding=\"latin-1\") as f:\n",
    "\n",
    "            for line in lna_lines:\n",
    "                f.write(line + \"\\n\")\n",
    "\n",
    "        # ===================================================\n",
    "        # Write Sach\n",
    "        # ===================================================\n",
    "\n",
    "        with open(self.sach_file, \"w\", encoding=\"latin-1\") as f:\n",
    "\n",
    "            for line in sach_lines:\n",
    "                f.write(line + \"\\n\")\n",
    "\n",
    "        print(\"\\n\" + \"=\" * 60)\n",
    "        print(\"Finished\")\n",
    "        print(\"=\" * 60)\n",
    "\n",
    "        print(f\"\\nLNA file  : {self.lna_file}\")\n",
    "        print(f\"Sach file : {self.sach_file}\")\n",
    "\n",
    "        print(f\"\\nLNA records  : {len(lna_lines)}\")\n",
    "        print(f\"Sach records : {len(sach_lines)}\")\n",
    "\n",
    "\n",
    "# ==========================================================\n",
    "# MAIN\n",
    "# ==========================================================\n",
    "\n",
    "def main():\n",
    "\n",
    "    pkt_file = r\"C:\\Users\\praka\\Desktop\\txt_file\\8026-1G-LNE_original.PKT\"\n",
    "\n",
    "    assistant = GeografAssistant(pkt_file)\n",
    "\n",
    "    assistant.process()\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n",
    "\n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b522b9f-088d-4310-898f-22a0b0f4dfa2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.25"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
